sonar.projectKey=achat
sonar.projectName=achat
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.coverage.minimum=0

sonar.host.url=http://localhost:9000